# Generated by Django 3.2.4 on 2021-06-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile'),
        ),
    ]
