# Generated by Django 3.2.4 on 2021-06-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile'),
        ),
    ]
