# Generated by Django 3.2.4 on 2021-06-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_testimonial_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_published',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
