# Generated by Django 3.2.4 on 2021-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210616_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
