# Generated by Django 3.2.4 on 2021-06-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_profile_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
