# Generated by Django 3.2.4 on 2021-06-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_testimonial_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial',
            new_name='body',
        ),
    ]
