# Generated by Django 3.2.4 on 2021-06-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_testimonial_testimonial_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
