# Generated by Django 3.2.4 on 2021-06-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
    ]
